version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000
    volumes:
      - .:/app  # Mount current directory to /app inside the container
    environment:
      - ENV=production  # You can set the environment to production
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000  # Command to run FastAPI app

  # Example: PostgreSQL as a database (optional)
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
