version: '3.8'

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8080:8080"  # Expose FastAPI on port 8000
    volumes:
      - .:/app  # Mount current directory to /app inside the container
    environment:
      - ENV=production  # You can set the environment to production
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080  # Command to run FastAPI app
