import pandas as pd
import os

# Define the path to the folder
folder_path = 'new data'

# Load the parameter_list file to get the column headers
parameter_list_path = os.path.join(folder_path, 'parameter_list.csv')
parameter_list = pd.read_csv(parameter_list_path, header=None).iloc[0].tolist()

# Initialize an empty list to store the rows
data_rows = []

# Loop through the params_1.csv to params_5000.csv files
for i in range(1, 5001):
    param_file = os.path.join(folder_path, f'params_{i}.csv')
    param_data = pd.read_csv(param_file, header=None).iloc[0].tolist()  # Read the single row of each file
    data_rows.append(param_data)

# Create the DataFrame with the appropriate columns
df = pd.DataFrame(data_rows, columns=parameter_list)

# Optionally, save the DataFrame to a new CSV file
df.to_csv(os.path.join(folder_path, 'combined_data.csv'), index=False)

# Display the DataFrame
print(df)
