name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    - name: Authenticate with AWS ECR
      run: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${{ secrets.ECR_URL }}

    - name: Build and Push Docker Image
      run: |
        docker build -t my-app .
        docker tag my-app:latest ${{ secrets.ECR_URL }}:latest
        docker push ${{ secrets.ECR_URL }}:latest

    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Pulling Docker image from ECR..."
          docker pull ${{ secrets.ECR_URL }}:latest
          echo "Stopping and removing old containers..."
          docker stop my-app || true
          docker rm my-app || true
          echo "Running new container..."
          docker run -d -p 80:80 --name my-app ${{ secrets.ECR_URL }}:latest
