name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  AWS_REGION: "us-east-2"
  ECR_URL: ${{ secrets.ECR_URL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Authenticate with AWS ECR
    - name: Authenticate with AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        region: ${{ env.AWS_REGION }}

    # Step 3: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t my-app .
        docker tag my-app:latest $ECR_URL:latest
        docker push $ECR_URL:latest

    # Step 4: SSH into Server and Deploy
    - name: SSH into Server and Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Stopping and removing old containers..."
          docker stop my-app || true
          docker rm my-app || true
          
          echo "Pulling Docker image from ECR..."
          docker pull $ECR_URL:latest
          
          echo "Running new container..."
          docker run -d -p 80:80 --name my-app $ECR_URL:latest

    # Step 5: Verify Deployment
    - name: Verify Deployment
      run: |
        curl -I http://${{ secrets.EC2_HOST }}
