name: Deploy Application to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Fix and Install Dependencies
      run: |
        echo "Resolving package conflicts..."
        sudo apt-get update
        # Identify and remove conflicting container runtimes
        sudo apt-get purge -y containerd containerd.io || true
        sudo apt-get autoremove -y
        
        # Clear held packages
        sudo apt-get install -f || true
        sudo dpkg --configure -a || true

        # Install containerd.io and other dependencies
        sudo apt-get install -y docker.io containerd.io nginx unzip awscli

    - name: Configure Nginx
      run: |
        echo "Updating Nginx configuration..."
        cat <<EOL | sudo tee /etc/nginx/sites-available/default
        server {
            listen 80;
            server_name 3.17.13.87;

            location / {
                proxy_pass http://127.0.0.1:8080;
                proxy_set_header Host \$host;
                proxy_set_header X-Real-IP \$remote_addr;
                proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto \$scheme;
            }
        }
        EOL
        sudo nginx -t
        sudo systemctl restart nginx

    - name: Authenticate AWS ECR
      run: |
        echo "Authenticating with AWS ECR..."
        aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 430118853371.dkr.ecr.us-east-2.amazonaws.com/mi_fatality_prediction

    - name: Pull and Run Docker Container
      run: |
        echo "Pulling and running Docker container..."
        docker pull 430118853371.dkr.ecr.us-east-2.amazonaws.com/mi_fatality_prediction:latest
        docker stop my_container || true
        docker rm my_container || true
        docker run -d --name my_container -p 8080:8080 430118853371.dkr.ecr.us-east-2.amazonaws.com/mi_fatality_prediction:latest

    - name: Verify Application
      run: |
        echo "Verifying application..."
        curl http://3.17.13.87:80 || exit 1
