name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 4: Login to AWS ECR
      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      # Step 5: Build and tag Docker image
      - name: Build Docker image
        id: build-image
        run: |
          docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/mi_fatality_prediction:latest .

      # Step 6: Push Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/mi_fatality_prediction:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 3: Login to AWS ECR
      - name: Login to AWS ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      # Step 4: Add SSH key for EC2 access
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 5: Add EC2 host to known hosts
      - name: Add EC2 host to known hosts
        run: |
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Step 6: Deploy Docker container to EC2
      - name: Deploy Docker container to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          ssh -o "StrictHostKeyChecking=no" $EC2_USER@$EC2_HOST << 'EOF'
          set -e  # Exit immediately if a command exits with a non-zero status

          # Log the start of the deployment process
          echo "Starting deployment to EC2 instance at $(date)..."

          # Update package database
          echo "Updating package database..."
          sudo apt-get update -y

          # Install Docker if not installed
          echo "Checking Docker installation..."
          if ! command -v docker &> /dev/null; then
            echo "Docker is not installed. Installing Docker..."
            sudo apt-get install -y docker.io
          else
            echo "Docker is already installed."
          fi

          # Start Docker service
          echo "Ensuring Docker service is running..."
          sudo systemctl start docker
          sudo systemctl enable docker

          # Authenticate with AWS ECR
          echo "Authenticating with AWS ECR..."
          aws ecr get-login-password --region $AWS_REGION | sudo docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
          if [ $? -ne 0 ]; then
            echo "ECR authentication failed. Exiting."
            exit 1
          fi

          # Pull Docker image from ECR
          echo "Pulling Docker image from ECR..."
          sudo docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/mi_fatality_prediction:latest
          if [ $? -ne 0 ]; then
            echo "Failed to pull Docker image. Exiting."
            exit 1
          fi

          # Stop and remove any running containers
          echo "Stopping and removing existing containers (if any)..."
          RUNNING_CONTAINER=$(sudo docker ps -q)
          if [ -n "$RUNNING_CONTAINER" ]; then
            echo "Stopping running container: $RUNNING_CONTAINER"
            sudo docker stop $RUNNING_CONTAINER
            sudo docker rm $RUNNING_CONTAINER
          else
            echo "No running containers found."
          fi

          # Run Docker container
          echo "Running the new Docker container..."
          sudo docker run -d -p 80:80 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/mi_fatality_prediction:latest
          if [ $? -ne 0 ]; then
            echo "Failed to start the Docker container. Exiting."
            exit 1
          fi

          echo "Deployment completed successfully at $(date)!"
          EOF
